import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F9FA",
    alignItems: "center",
    justifyContent: "center",
  },
  appName: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#82C491",
    marginBottom: 30,
  },
  card: {
    width: "94%",
    backgroundColor: "#F3FAF4",
    borderRadius: 30,
    paddingHorizontal: 20,
    paddingVertical: 35,
    alignItems: "center",
  },
  weatherRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 25,
  },
  weatherBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "white",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#FAD7A0",
    width: "45%",
  },
  weatherDate: { fontSize: 10, color: "#999" },
  weatherTemp: { fontSize: 18, fontWeight: "bold", color: "#333" },
  sprayBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "white",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "#D5F5E3",
    width: "52%",
  },
  sprayTitle: { fontSize: 10, color: "#999" },
  sprayStatus: { fontSize: 15, fontWeight: "bold", color: "#333" },
  infoIconCircle: {
    backgroundColor: "#FFE5B4",
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  locationContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginBottom: 35,
    paddingHorizontal: 5,
    minHeight: 45,
  },
  locationText: {
    flex: 1,
    fontSize: 12,
    color: "#666",
    marginHorizontal: 10,
    lineHeight: 18,
  },
  allowLink: { fontSize: 14, fontWeight: "bold", color: "#3F51B5" },
  workflow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 45,
  },
  step: { alignItems: "center" },
  dashedBox: {
    width: 60,
    height: 60,
    borderStyle: "dashed",
    borderWidth: 1.5,
    borderColor: "#E9C46A",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
  },
  stepText: { fontSize: 13, marginTop: 8, fontWeight: "bold", color: "#333" },
  mainButton: {
    backgroundColor: "#ABE0AC",
    paddingVertical: 18,
    paddingHorizontal: 70,
    borderRadius: 35,
  },
  buttonText: { color: "white", fontSize: 20, fontWeight: "bold" },
});
