// src/features/profile/styles/profileLoggedIn-style.ts
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FFF", paddingTop: 60 },
  appName: {
    textAlign: "center",
    fontSize: 18,
    fontWeight: "600",
    color: "#ABE0AC",
    marginBottom: 25,
  },
  profileSection: {
    flexDirection: "row",
    paddingHorizontal: 25,
    marginBottom: 30,
  },
  avatarPlaceholder: {
    width: 75,
    height: 75,
    backgroundColor: "#F2F2F2",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  profileTextContainer: { flex: 1, marginLeft: 15 },
  userName: { fontSize: 18, fontWeight: "bold", color: "#333" },
  userBio: { fontSize: 11, color: "#777", marginTop: 2 },
  vatoButton: {
    borderWidth: 1,
    borderColor: "#ABE0AC",
    borderRadius: 18,
    paddingVertical: 3,
    width: 120,
    alignItems: "center",
    marginTop: 8,
  },
  vatoText: { color: "#ABE0AC", fontSize: 15, fontWeight: "500" },
  tabBar: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#F2F2F2",
  },
  tabItem: { flex: 1, alignItems: "center", paddingVertical: 12 },
  activeTabBorder: { borderBottomWidth: 3, borderBottomColor: "#ABE0AC" },
  tabLabel: { fontSize: 13, color: "#999", fontWeight: "600" },
  activeLabel: { color: "#333" },
  listContainer: { paddingBottom: 20 },
  listItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    paddingHorizontal: 25,
    borderBottomWidth: 0.5,
    borderBottomColor: "#F0F0F0",
    backgroundColor: "white",
  },
  itemImagePlaceholder: {
    width: 50,
    height: 50,
    backgroundColor: "#F8F8F8",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  itemTextInfo: { flex: 1, marginLeft: 15 },
  itemDate: { fontSize: 10, color: "#AAA" },
  itemTitle: { fontSize: 14, fontWeight: "700", color: "#444" },
  deleteAction: {
    backgroundColor: "#E63946",
    justifyContent: "center",
    alignItems: "center",
    width: 70,
    height: "100%",
  },
  activityCard: {
    marginHorizontal: 20,
    marginTop: 15,
    borderRadius: 15,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#F0F0F0",
    overflow: "hidden",
    elevation: 2,
  },
  postImageContainer: {
    width: "100%",
    height: 180,
    backgroundColor: "#F9F9F9",
    justifyContent: "center",
    alignItems: "center",
  },
  imageNote: { fontSize: 10, color: "#CCC", marginTop: 5 },
  postContent: { padding: 15 },
  postHeader: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  smallAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#EEE",
    marginRight: 10,
  },
  postUserName: { fontSize: 13, fontWeight: "bold", color: "#4A55A2" },
  postDate: { fontSize: 10, color: "#999" },
  postTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 4,
  },
  postDescription: { fontSize: 13, color: "#666", marginBottom: 15 },
  postFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#F5F5F5",
    paddingTop: 10,
  },
  interactionGroup: { flexDirection: "row" },
  iconBtn: { flexDirection: "row", alignItems: "center", marginRight: 20 },
  interactionText: {
    fontSize: 14,
    color: "#728096",
    marginLeft: 8,
    fontWeight: "500",
  },
});
